(function(c){function d(){}function n(a){A=[a]}function p(a,h,f,g){try{g=a&&a.apply(h.context||h,f)}catch(s){g=false}return g}function B(a){return/\?/.test(a)?"&":"?"}function I(a){function h(k){J++||(K(),o&&(C[i]={s:[k]}),s&&(k=s.apply(a,[k])),p(a.success,a,[k,t]),p(g,a,[a,t]))}function f(k){J++||(K(),o&&k!=x&&(C[i]=k),p(a.error,a,[a,k]),p(g,a,[a,k]))}a=c.extend({},L,a);var g=a.complete,s=a.dataFilter,M=a.callbackParameter,l=a.callback,N=a.cache,o=a.pageCache,V=a.charset,i=a.url,u=a.data,W=a.timeout,
O,J=0,K=d,e,D,T;return a.abort=function(){!J++&&K()},p(a.beforeSend,a,[a])===false||J?a:(i=i||v,u=u?typeof u=="string"?u:c.param(u,a.traditional):v,i+=u?B(i)+u:v,M&&(i+=B(i)+encodeURIComponent(M)+"=?"),!N&&!o&&(i+=B(i)+"_"+(new Date).getTime()+"="),i=i.replace(/=\?(&|$)/,"="+l+"$1"),o&&(O=C[i])?O.s?h(O.s[0]):f(O):(y[l]=n,e=c(j)[0],e.id=P+U++,V&&(e[E]=V),b&&b.version()<11.6?((D=c(j)[0]).text="document.getElementById('"+e.id+"')."+w+"()"):(e[Q]=Q),!(z in e)&&F in e&&(e.htmlFor=e.id,e.event=q),e[z]=
e[w]=e[F]=function(k){if(!e[R]||/loaded|complete/.test(e[R])){try{e[q]&&e[q]()}catch(X){}k=A;A=0;k?h(k[0]):f(S)}},e.src=i,K=function(){T&&clearTimeout(T);e[F]=e[z]=e[w]=null;r[m](e);D&&r[m](D)},r[G](e,H),D&&r[G](D,H),T=W>0&&setTimeout(function(){f(x)},W)),a)}var Q="async",E="charset",v="",S="error",G="insertBefore",P="_jqjsp",q="onclick",w="on"+S,z="onload",F="onreadystatechange",R="readyState",m="removeChild",j="<script>",t="success",x="timeout",y=window,r=c("head")[0]||document.documentElement,
H=r.firstChild,C={},U=0,A,L={callback:P,url:location.href},b=y.opera;I.setup=function(a){c.extend(L,a)};c.jsonp=I})(jQuery);var suggestionsearch_enable=function(){jQuery("#navbar-query").searchAutocomplete({maxResults:6,alwaysScrollIntoView:false,resultsDiv:jQuery("#navbar-suggestionsearch"),keyboardControl:true});jQuery("#navbar-query").attr("autocomplete","off");repositionSuggestionSearch()},repositionSuggestionSearch=function(){var c=jQuery("#navbar-query"),d=c.position(),n=c.width();c=c.height();jQuery("#navbar-suggestionsearch").css({left:d.left+0+"px",top:d.top+c+11+"px",width:n+115+"px"})},suggestionsearch_disable=
function(){jQuery("#navbar-query").stopSearchAutocomplete({resultsDiv:jQuery("#navbar-suggestionsearch")});jQuery("#navbar-query").attr("autocomplete","on")},suggestionsearch_dropdown_choice=function(c){"all"==c.value?suggestionsearch_enable():suggestionsearch_disable()};function trackAndClick(c,d,n){(new Image).src="/rg/"+c+"/"+d+"/images/b.gif";setTimeout(function(){document.location=n.href},0);return false}
jQuery(document).ready(function(){var c=jQuery('#nb_search select[name="s"]');if(c.length>0){c=c[0];suggestionsearch_dropdown_choice(c)}});
(function(c){c.fn.searchAutocomplete=function(d){function n(b){p();jQuery(b).addClass("highlighted")}function p(){j.find("a.highlighted").removeClass("highlighted")}function B(){var b=j.find("a.highlighted");b.length>0?b.first().get(0).click():jQuery("#navbar-form").submit()}function I(){if(j.find("a").length>0){var b=j.find("a.highlighted");if(b.length>0){b=b.first();var a=b.prev("a");a.length>0&&a.first().addClass("highlighted");b.removeClass("highlighted")}}}function Q(){var b=j.find("a");if(b.length>
0){var a=j.find("a.highlighted");if(a.length>0){b=a.first();a=b.next("a");if(a.length>0){a.first().addClass("highlighted");b.removeClass("highlighted")}}else b.first().addClass("highlighted")}}function E(){repositionSuggestionSearch();j.css("display","block")}function v(){j.css("display","none")}function S(){j.css({opacity:0,filter:"alpha(opacity=0)"})}function G(b){if(b){b=b.toLowerCase();if(b.length>20)b=b.substr(0,20);b=b.replace(/^\s*/,"").replace(/[ ]+/g,"_");if(A.test(b))b=b.replace(/[\u00e0\u00c0\u00e1\u00c1\u00e2\u00c2\u00e3\u00c3\u00e4\u00c4\u00e5\u00c5\u00e6\u00c6]/g,
"a").replace(/[\u00e7\u00c7]/g,"c").replace(/[\u00e8\u00c8\u00e9\u00c9\u00ea\u00ca\u00eb\u00cb]/g,"e").replace(/[\u00ec\u00cd\u00ed\u00cd\u00ee\u00ce\u00ef\u00cf]/g,"i").replace(/[\u00f0\u00d0]/g,"d").replace(/[\u00f1\u00d1]/g,"n").replace(/[\u00f2\u00d2\u00f3\u00d3\u00f4\u00d4\u00f5\u00d5\u00f6\u00d6\u00f8\u00d8]/g,"o").replace(/[\u00f9\u00d9\u00fa\u00da\u00fb\u00db\u00fc\u00dc]/g,"u").replace(/[\u00fd\u00dd\u00ff]/g,"y").replace(/[\u00fe\u00de]/g,"t").replace(/[\u00df]/g,"ss");return b=b.replace(/[\W]/g,
"")}return""}function P(){w(m.val())}function q(b,a){if(b&&a&&a.length<=b.length&&b.substr(0,a.length)===a)return true;return false}function w(b){var a=G(b);if(a.length==0){v();x=t=""}else if(a!==t){E();c.jsonp({charset:"UTF-8",dataType:"jsonp",callback:"imdb$"+a,url:"//sg.media-imdb.com/suggests/"+a.substr(0,1)+"/"+a+".json",error:function(h,f){if(f==="error"&&a.length>1)q(t,x)?F(a):w(a.substr(0,a.length-1))},success:function(h){x=a;y=h;z(h,a)},pageCache:pageCacheSetting});t=a}}function z(b){var a=
"",h="";if(typeof c("#nb_search").attr("data-hostname")!="undefined")h="http://"+c("#nb_search").attr("data-hostname");for(var f=0;f<b.d.length&&f<C;f+=1){var g=b.d[f],s="";if(c("#megaMenu").length)s="nv_";var M=s+"sr_"+(f+1),l=g.id,N="film-40x54.png",o;if(q(l,"nm")){o=h+"/name/"+l+"/";N="people-40x54.png"}else if(q(l,"tt"))o=h+"/title/"+l+"/";else if(q(l,"http://"))o=l;if(o){l={url:o,title:g.l,detail:g.s,placeholder:N};if(g.i)l.img={url:g.i[0].replace("._V1_.jpg","._V1._SX40_CR0,0,40,54_.jpg"),width:40,
height:54};if(g.y)l.extra="("+g.y+")";a+=R(l,M)}}if(a.length>0){E();f=m.val();b=f.replace(U," ");f=jQuery("<div/>").text(f).html();a+='<a class="moreResults" href="';a+=h+"/find?s=all&q="+b+"&ref_="+s+'sr_sm">';a+='<span class="message">See all results for "<span class="query">'+f+'</span>"</span>&nbsp;<span class="raquo">&raquo;</span>';a+="</a>";j.html(a);j.find("a").hover(function(){n(this)},function(){})}}function F(b){for(var a=[],h=[],f=0;f<y.d.length;f+=1){var g=y.d[f];G(g.l).match(b)?a.push(g):
h.push(g)}z({d:a.concat(h)},b)}function R(b,a){a='<a href="'+b.url+"?ref_="+a+'" class="poster"';a+=">";if(b.img){a+='<img src="'+b.img.url+'"';a+=" style=\"background:url('http://i.media-imdb.com/images/mobile/"+b.placeholder+"')\"";if(b.img.width&&b.img.height)a+=' width="'+b.img.width+'" height="'+b.img.height+'"';a+=">"}else if(b.placeholder)a+='<img src="http://i.media-imdb.com/images/mobile/'+b.placeholder+'">';a+='<div class="suggestionlabel">';a+='<span class="title">'+b.title+"</span>";if(b.extra)a+=
' <span class="extra">'+b.extra+"</span>";if(b.detail)a+='<div class="detail">'+b.detail+"</div>";a+="</div></a>";return a}if(typeof d=="undefined")d={};var m=jQuery(this),j="resultsDiv"in d?d.resultsDiv:jQuery("#autocomplete"),t="",x="",y="",r,H,C="maxResults"in d?d.maxResults:3,U=/[^\w\u00e0\u00c0\u00e1\u00c1\u00e2\u00c2\u00e3\u00c3\u00e4\u00c4\u00e5\u00c5\u00e6\u00c6\u00e7\u00c7\u00e8\u00c8\u00e9\u00c9\u00ea\u00ca\u00eb\u00cb\u00ec\u00cd\u00ed\u00cd\u00ee\u00ce\u00ef\u00cf\u00f0\u00d0\u00f1\u00d1\u00f2\u00d2\u00f3\u00d3\u00f4\u00d4\u00f5\u00d5\u00f6\u00d6\u00f8\u00d8\u00f9\u00d9\u00fa\u00da\u00fb\u00db\u00fc\u00dc\u00fd\u00dd\u00ff\u00fe\u00de\u00df]/g,
A=/[\u00e0\u00c0\u00e1\u00c1\u00e2\u00c2\u00e3\u00c3\u00e4\u00c4\u00e5\u00c5\u00e6\u00c6\u00e7\u00c7\u00e8\u00c8\u00e9\u00c9\u00ea\u00ca\u00eb\u00cb\u00ec\u00cd\u00ed\u00cd\u00ee\u00ce\u00ef\u00cf\u00f0\u00d0\u00f1\u00d1\u00f2\u00d2\u00f3\u00d3\u00f4\u00d4\u00f5\u00d5\u00f6\u00d6\u00f8\u00d8\u00f9\u00d9\u00fa\u00da\u00fb\u00db\u00fc\u00dc\u00fd\u00dd\u00ff\u00fe\u00de\u00df]/,L="keyboardControl"in d?d.keyboardControl:false;alwaysScrollIntoView="alwaysScrollIntoView"in d?d.alwaysScrollIntoView:true;
pageCacheSetting=c.browser.msie==true?false:true;c(document).mousedown(function(b){H=c(b.target)});m.focus(function(){alwaysScrollIntoView&&this.scrollIntoView();if(m.val().length>0){w(m.val());E()}});m.blur(function(){r=H.parents("#navbar-suggestionsearch").length?setTimeout(S,300):setTimeout(v,300)});m.keydown(function(b){if(L)if(b.keyCode==38){m.focus();I();return false}else if(b.keyCode==40){m.focus();Q();return false}else if(b.keyCode==13){B();return false}else if(b.keyCode==27){p();v();return false}m.focus();
r=setTimeout(P,0)})};c.fn.stopSearchAutocomplete=function(d){if(typeof d=="undefined")d={};var n=jQuery(this);d="resultsDiv"in d?d.resultsDiv:jQuery("#autocomplete");n.unbind("focus");n.unbind("blur");n.unbind("keydown");d.css("display","none")}})(jQuery);
